# Generated by Django 4.0.5 on 2022-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_created_recipe_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
