# Generated by Django 4.0.5 on 2022-08-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredientrecipe_quantity_alter_recipe_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_recipe', to='recipe.recipe')),
            ],
        ),
    ]
