# Generated by Django 4.0.5 on 2022-09-10 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_cookingrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='WeigthRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitaire', models.FloatField(null=True)),
                ('cru', models.FloatField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_recipe', to='recipe.recipe')),
            ],
        ),
    ]
