# Generated by Django 4.0.5 on 2022-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_title_weigthrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weigthrecipe',
            name='cru',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='weigthrecipe',
            name='unitaire',
            field=models.FloatField(default=100),
        ),
    ]
