# Generated by Django 4.0.5 on 2022-09-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_weigthrecipe_cru_alter_weigthrecipe_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weigthrecipe',
            name='cru',
            field=models.FloatField(default=13.5),
        ),
        migrations.AlterField(
            model_name='weigthrecipe',
            name='unitaire',
            field=models.FloatField(default=13.5),
        ),
    ]
